# Generated by Django 4.1.5 on 2023-01-30 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='CityCorporationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bng', models.CharField(blank=True, max_length=100, null=True)),
                ('name_eng', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'city_corporation',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DistrictModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bng', models.CharField(blank=True, max_length=100, null=True)),
                ('name_eng', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'district',
            },
        ),
        migrations.CreateModel(
            name='DivisionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bng', models.CharField(blank=True, max_length=100, null=True)),
                ('name_eng', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'division',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='JobTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bng', models.CharField(blank=True, max_length=100, null=True)),
                ('name_eng', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'job_type',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OTPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(db_index=True, max_length=20)),
                ('user_type', models.CharField(blank=True, max_length=50, null=True)),
                ('otp_number', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'otp_storage',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionCatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bng', models.CharField(blank=True, max_length=100, null=True)),
                ('name_eng', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'profession_category',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UpazilaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bng', models.CharField(blank=True, max_length=100, null=True)),
                ('name_eng', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'district',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peshajibi.districtmodel'),
                ),
            ],
            options={
                'db_table': 'upazila',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UnionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bng', models.CharField(blank=True, max_length=100, null=True)),
                ('name_eng', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'upazila',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peshajibi.upazilamodel'),
                ),
            ],
            options={
                'db_table': 'union',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bng', models.CharField(blank=True, max_length=100, null=True)),
                ('name_eng', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'profession_cat',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peshajibi.professioncatmodel'),
                ),
            ],
            options={
                'db_table': 'profession',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='districtmodel',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peshajibi.divisionmodel'),
        ),
        migrations.CreateModel(
            name='CityCorporationThanaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bng', models.CharField(blank=True, max_length=100, null=True)),
                ('name_eng', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'city_corporation',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peshajibi.citycorporationmodel'),
                ),
            ],
            options={
                'db_table': 'city_corporation_thana',
                'ordering': ['id'],
            },
        ),
    ]
