# Generated by Django 4.1.5 on 2023-02-02 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('peshajibi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericAdsServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'generic_ads_services',
            },
        ),
        migrations.AlterModelOptions(
            name='districtmodel',
            options={'ordering': ['id']},
        ),
        migrations.CreateModel(
            name='TransportAdsService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_medium', models.CharField(db_index=True, max_length=100)),
                ('product_name', models.CharField(db_index=True, max_length=100)),
                ('product_weight', models.CharField(blank=True, max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'from_district',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='from_district_transports',
                        to='peshajibi.districtmodel',
                    ),
                ),
                (
                    'from_division',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='from_division_transports',
                        to='peshajibi.divisionmodel',
                    ),
                ),
                (
                    'from_upazila',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='from_upazila_transports',
                        to='peshajibi.upazilamodel',
                    ),
                ),
                (
                    'to_district',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='to_district_transports',
                        to='peshajibi.districtmodel',
                    ),
                ),
                (
                    'to_division',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='to_division_transports',
                        to='peshajibi.divisionmodel',
                    ),
                ),
                (
                    'to_upazila',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='to_upazila_transports',
                        to='peshajibi.upazilamodel',
                    ),
                ),
            ],
            options={
                'db_table': 'transport_ads_services',
            },
        ),
        migrations.CreateModel(
            name='AdsServicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_type', models.CharField(max_length=50)),
                ('is_negotiable', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'content_type',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
                ),
                (
                    'profession_cat',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='ads_services',
                        to='peshajibi.professioncatmodel',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='my_ads', to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                'db_table': 'ads_services',
            },
        ),
    ]
