# Generated by Django 4.1.5 on 2023-02-15 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peshajibi', '0003_alter_adsservicesmodel_options_and_more'),
        ('users', '0002_accountsmodel_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisionuserprofilemodel',
            name='permanent_district',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='permanent_district_users',
                to='peshajibi.districtmodel',
            ),
        ),
        migrations.AlterField(
            model_name='divisionuserprofilemodel',
            name='permanent_division',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='permanent_division_users',
                to='peshajibi.divisionmodel',
            ),
        ),
        migrations.AlterField(
            model_name='divisionuserprofilemodel',
            name='permanent_union',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='permanent_union_users',
                to='peshajibi.unionmodel',
            ),
        ),
        migrations.AlterField(
            model_name='divisionuserprofilemodel',
            name='permanent_upazila',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='permanent_upazila_users',
                to='peshajibi.upazilamodel',
            ),
        ),
        migrations.AlterField(
            model_name='divisionuserprofilemodel',
            name='present_district',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='current_district_users',
                to='peshajibi.districtmodel',
            ),
        ),
        migrations.AlterField(
            model_name='divisionuserprofilemodel',
            name='present_division',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='current_division_users',
                to='peshajibi.divisionmodel',
            ),
        ),
        migrations.AlterField(
            model_name='divisionuserprofilemodel',
            name='present_union',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='current_union_users',
                to='peshajibi.unionmodel',
            ),
        ),
        migrations.AlterField(
            model_name='divisionuserprofilemodel',
            name='present_upazila',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='current_upazila_users',
                to='peshajibi.upazilamodel',
            ),
        ),
        migrations.AlterField(
            model_name='divisionuserprofilemodel',
            name='profession',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peshajibi.professionmodel'
            ),
        ),
    ]
