# Generated by Django 4.1.5 on 2023-02-15 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peshajibi', '0003_alter_adsservicesmodel_options_and_more'),
        ('users', '0003_alter_divisionuserprofilemodel_permanent_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citycorporationuserprofilemodel',
            name='permanent_city',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='permanent_city_users',
                to='peshajibi.citycorporationmodel',
            ),
        ),
        migrations.AlterField(
            model_name='citycorporationuserprofilemodel',
            name='permanent_thana',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='permanent_thana_users',
                to='peshajibi.citycorporationthanamodel',
            ),
        ),
        migrations.AlterField(
            model_name='citycorporationuserprofilemodel',
            name='present_city',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='current_city_users',
                to='peshajibi.citycorporationmodel',
            ),
        ),
        migrations.AlterField(
            model_name='citycorporationuserprofilemodel',
            name='present_thana',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='current_thana_users',
                to='peshajibi.citycorporationthanamodel',
            ),
        ),
        migrations.AlterField(
            model_name='citycorporationuserprofilemodel',
            name='profession',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peshajibi.professionmodel'
            ),
        ),
    ]
