# Generated by Django 4.1.5 on 2023-02-15 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_accountsmodel_is_donate_blood_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountsmodel',
            old_name='share_profile',
            new_name='is_share_profile',
        ),
    ]
