# Generated by Django 4.1.5 on 2023-02-02 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peshajibi', '0002_genericadsservicemodel_alter_districtmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adsservicesmodel',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='genericadsservicemodel',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='transportadsservice',
            options={'ordering': ['-id']},
        ),
    ]
