# Generated by Django 4.1.5 on 2023-03-05 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peshajibi', '0005_alter_adsservicetypeschemamodel_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adsservicesmodel',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='adsservicesmodel',
            name='profession_cat',
        ),
        migrations.RemoveField(
            model_name='adsservicesmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='GenericAdsServiceModel',
        ),
        migrations.DeleteModel(
            name='JobTypeModel',
        ),
        migrations.RemoveField(
            model_name='transportadsservice',
            name='from_district',
        ),
        migrations.RemoveField(
            model_name='transportadsservice',
            name='from_division',
        ),
        migrations.RemoveField(
            model_name='transportadsservice',
            name='from_upazila',
        ),
        migrations.RemoveField(
            model_name='transportadsservice',
            name='to_district',
        ),
        migrations.RemoveField(
            model_name='transportadsservice',
            name='to_division',
        ),
        migrations.RemoveField(
            model_name='transportadsservice',
            name='to_upazila',
        ),
        migrations.DeleteModel(
            name='AdsServicesModel',
        ),
        migrations.DeleteModel(
            name='TransportAdsService',
        ),
    ]
