# Generated by Django 4.1.5 on 2023-03-05 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peshajibi', '0006_remove_adsservicesmodel_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'service_type',
                    models.CharField(
                        choices=[('offer_service', 'সেবা দিতে চাই'), ('take_service', 'সেবা নিতে চাই')], max_length=100
                    ),
                ),
                (
                    'service_medium_or_item',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('fridge', 'ফ্রিজ'),
                            ('mobile', 'মোবাইল'),
                            ('microbus', 'মাইক্রোবাস'),
                            ('motorcycle', 'মোটর সাইকেল'),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ('product_name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('product_weight', models.CharField(blank=True, max_length=100, null=True)),
                ('is_negotiable', models.BooleanField(default=False)),
                ('notice_period_days', models.CharField(blank=True, max_length=2, null=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('job_created_at', models.DateTimeField(auto_now_add=True)),
                ('job_updated_at', models.DateTimeField(auto_now=True)),
                (
                    'ads_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='ads',
                        to='peshajibi.professioncatmodel',
                    ),
                ),
                (
                    'from_district',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='from_district_transports',
                        to='peshajibi.districtmodel',
                    ),
                ),
                (
                    'from_division',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='from_division_transports',
                        to='peshajibi.divisionmodel',
                    ),
                ),
                (
                    'from_upazila',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='from_upazila_transports',
                        to='peshajibi.upazilamodel',
                    ),
                ),
                (
                    'profession',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='peshajibi.professionmodel'
                    ),
                ),
                (
                    'to_district',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='to_district_transports',
                        to='peshajibi.districtmodel',
                    ),
                ),
                (
                    'to_division',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='to_division_transports',
                        to='peshajibi.divisionmodel',
                    ),
                ),
                (
                    'to_upazila',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='to_upazila_transports',
                        to='peshajibi.upazilamodel',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='my_ads', to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                'db_table': 'ads',
                'ordering': ['-id'],
            },
        ),
    ]
