# Generated by Django 4.1.5 on 2023-03-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peshajibi', '0007_ads'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adsservicetypeschemamodel',
            options={'ordering': ['service_id']},
        ),
        migrations.AddField(
            model_name='adsservicetypeschemamodel',
            name='service_level',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
