# Generated by Django 4.1.5 on 2023-03-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peshajibi', '0008_alter_adsservicetypeschemamodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professioncatmodel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='professionmodel',
            options={},
        ),
        migrations.AddField(
            model_name='professioncatmodel',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/profession_cat/'),
        ),
        migrations.AddField(
            model_name='professionmodel',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/profession/'),
        ),
    ]
