# Generated by Django 4.1.5 on 2023-03-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peshajibi', '0009_alter_professioncatmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='service_provide_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ads',
            name='service_provide_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
